name: Release

on:
  push:
    branches:
      - master
      - feature/pipeline

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - run: git fetch --unshallow
      - name: GitVersion
        id: gitversion
        uses: ./.github/actions/gitversion
        with:
          entrypoint: /bin/sh
          args: -c "echo \"##[set-output name=version;]$(/tools/dotnet-gitversion /showvariable semver)\""
      - name: Build For Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o ./dist/linux/amd64/pocket \
            -ldflags "-X main.productVersion=${{steps.gitversion.outputs.version}}"
      - name: Build For Mac
        run: |
          GOOS=darwin GOARCH=amd64 go build -o ./dist/darwin/amd64/pocket \
            -ldflags "-X main.productVersion=${{steps.gitversion.outputs.version}}"
      - name: Build For Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o ./dist/windows/amd64/pocket.exe \
            -ldflags "-X main.productVersion=${{steps.gitversion.outputs.version}}"
