name: Do Stuff

on: [push]

jobs:
  build:
    name: Try GitVersion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - run: git fetch --all --unshallow
      - name: GitVersion
        uses: ./.github/actions/gitversion
        with:
          entrypoint: /bin/sh
          args: -c "for h in $(ls .git/objects/); do for t in $(ls .git/objects/$h); do echo $h$t ; done; done"
