name: Release

on:
  push:
    branches:
      - master
      - feature/pipeline

jobs:
  build:
    name: Try GitVersion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - run: git fetch --unshallow
      - run: git checkout master
      - run: git checkout feature/pipeline
      - name: GitVersion
        id: gitversion
        uses: ./.github/actions/gitversion
        with:
          entrypoint: /bin/sh
          args: -c "echo \"##[set-output name=version;]$(/tools/dotnet-gitversion /showvariable semver)\""
      - run: echo ${{steps.gitversion.outputs.version}}
