name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - run: git fetch --unshallow
      - name: GitVersion
        id: gitversion
        uses: ./.github/actions/gitversion
        with:
          entrypoint: /bin/sh
          args: -c "echo \"##[set-output name=version;]$(/tools/dotnet-gitversion /showvariable semver)\""
      - name: Build For Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o ./dist/pocket-linux-amd64 \
            -ldflags "-X main.productVersion=${{steps.gitversion.outputs.version}}"
      - name: Build For Mac
        run: |
          GOOS=darwin GOARCH=amd64 go build -o ./dist/pocket-darwin-amd64 \
            -ldflags "-X main.productVersion=${{steps.gitversion.outputs.version}}"
      - name: Build For Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o ./dist/pocket-amd64.exe \
            -ldflags "-X main.productVersion=${{steps.gitversion.outputs.version}}"
      - name: Release
        run: |
          GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}} hub release create \
            -t $GITHUB_SHA \
            -a ./dist/pocket-linux-amd64 \
            -a ./dist/pocket-darwin-amd64 \
            -a ./dist/pocket-amd64.exe \
            -m ${{steps.gitversion.outputs.version}} \
            v${{steps.gitversion.outputs.version}}
