name: Do Stuff

on: [push]

jobs:
  build:
    name: Try GitVersion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: GitVersion
        uses: ./.github/actions/gitversion
        with:
          entrypoint: /bin/sh
          args: -c /tools/dotnet-gitversion

